name: Bug report
description: Create a report to help us improve Linq2db
body:
- type: markdown
  value: |
    # Describe your issue.
    
    If you have a question, first try to check our [documentation](https://linq2db.github.io/), especially [FAQ](https://linq2db.github.io/articles/FAQ.html) and search in [issues](https://github.com/linq2db/linq2db/issues) and [discussions](https://github.com/linq2db/linq2db/discussions) - maybe your question already answered there.

    If you still have questions or want to start general discussion, please create new topic in [discussions](https://github.com/linq2db/linq2db/discussions).

    If you are seeing an exception, include the full exceptions details (message and stack trace).

    ```
    Exception message:
    Stack trace:
    ```

    ### Steps to reproduce
    Include a complete code listing (or project/solution) that we can run to reproduce the issue.

    Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

    ```c#
    <code with error and mapping classes>
    ```

    ### Environment details
    linq2db version: *?*
    Database Server: *?*
    Database Provider: *?*
    Operating system: *?*
    
- type: dropdown
  id: dotnet
  attributes:
    label: .NET Framework
    options:
      - .Net 4.5
      - .Net 4.6
      - .Net 4.7.2
      - .Net Standard 2.0
      - .Net Core 2.1
      - .Net Standard 2.1
      - .Net Core 3.1
      - .Net Core 5.0
      - .Net Core 6.0
